name: Deploy Portfolio to AWS

on:
  push:
    branches:
      - main
    paths:
      - "index.html"
      - "css/**"
      - "js/**"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Upload website to S3
        run: |
          aws s3 sync . s3://srilekha1125-serverless-portfolio \
            --delete \
            --exclude "*" \
            --include "index.html" \
            --include "css/*" \
            --include "js/*"

      - name: Clear CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" \
            --paths "/*"
